dataset:
  name: Cityscapes 
  root: ../data/cityskapes 
  num_workers: 8
  pin_memory: true 



LeVIT256:
  backbone: LeVIT256 
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.0001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [224, 224]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/LeVIT_best_miou.pth
