name: "spareto"

train_dir: "data/train/"
train_label_path: "data/train_label.csv"
test_dir: "data/test/"
test_label_path: "data/test_label.csv"

checkpoint_dir: "checkpoint/"
checkpoint_best: "checkpoint/model_best.pt"
checkpoint_last: "checkpoint/model_latest.pt"

shuffle: True # Shuffle image data
use_cuda: True 
use_cpu: 4 # Number of workers 
learning_rate: 1e-3 # this could instead be read from argparser?
gamma: 7e-2
pin_memory: true 
epochs: 2
test_step: 20
batch_size: 32
img_size: 224
num_channels: 3 #number of color channels

step_size: 1

